--- #YAML:1.0
name:               URL-Checkout
version:            1.05
abstract:           Get one or multiple files from a remote location
author:
    - Juergen Weigert <jnw@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Cwd:                  0
    File::Path:           0
    File::Temp:           0
    String::ShellQuote:   0
    Test::More:           0
    Test::Pod::Coverage:  0
    Text::Sprintf::Named:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
